USE metro_cdmx;

INSERT INTO `stations`(name) VALUES
("Acatitla"),
("Aculco"),
("Agrícola Oriental"),
("Allende"),
("Apatlaco"),
("Aquiles Serdán"),
("Aragón"),
("Atlalilco"),
("Auditorio"),
("Autobuses del Norte"),
("Azcapotzalco"),
("Balbuena"),
("Balderas"),
("Barranca del Muerto"),
("Bellas Artes"),
("Bondojito"),
("Bosque de Aragón"),
("Boulevard Puerto Aéreo"),
("Buenavista"),
("Calle 11"),
("Camarones"),
("Canal del Norte"),
("Canal de San Juan"),
("Candelaria"),
("Centro Médico"),
("Cerro de la Estrella"),
("Chabacano"),
("Chapultepec"),
("Chilpancingo"),
("Ciudad Azteca"),
("Ciudad Deportiva"),
("Colegio Militar"),
("Constitución de 1917"),
("Constituyentes"),
("Consulado"),
("Copilco"),
("Coyoacán"),
("Coyuya"),
("Cuatro Caminos"),
("Cuauhtémoc"),
("Cuitláhuac"),
("Culhuacán"),
("Deportivo 18 de Marzo"),
("Deportivo Oceanía"),
("División del Norte"),
("Doctores"),
("Ecatepec"),
("Eduardo Molina"),
("Eje central"),
("El Rosario"),
("Ermita"),
("Escuadrón 201"),
("Etiopía/Plaza de la Transparencia"),
("Eugenia"),
("Ferrería"),
("Fray Servando"),
("Garibaldi"),
("General Anaya"),
("Gómez Farías"),
("Guelatao"),
("Guerrero"),
("Hangares"),
("Hidalgo"),
("Hospital 20 de Noviembre"),
("Hospital General"),
("Impulsora"),
("Indios Verdes"),
("Instituto del Petróleo"),
("Insurgentes"),
("Insurgentes Sur"),
("Isabel la Católica"),
("Iztacalco"),
("Iztapalapa"),
("Jamaica"),
("Juanacatlán"),
("Juárez"),
("Lagunilla"),
("La Paz"),
("La Raza"),
("La Viga"),
("La Villa-Basílica"),
("Lázaro Cárdenas"),
("Lindavista"),
("Los Reyes"),
("Miguel Ángel de Quevedo"),
("Martín Carrera"),
("Merced"),
("Mexicaltzingo"),
("Misterios"),
("Mixcoac"),
("Mixiuhca"),
("Moctezuma"),
("Morelos"),
("Múzquiz"),
("Nativitas"),
("Nezahualcóyotl"),
("Niños Héroes"),
("Nopalera"),
("Normal"),
("Norte 45"),
("Obrera"),
("Observatorio"),
("Oceanía"),
("Olímpica"),
("Olivos"),
("Panteones"),
("Pantitlán"),
("Parque de los venados"),
("Patriotismo"),
("Peñón Viejo"),
("Periférico Oriente"),
("Pino Suárez"),
("Plaza Aragón"),
("Polanco"),
("Politécnico"),
("Popotla"),
("Portales"),
("Potrero"),
("Puebla"),
("Refinería"),
("Revolución"),
("Ricardo Flores Magón"),
("Río de los Remedios"),
("Romero Rubio"),
("Salto del Agua"),
("San Andrés Tomatlán"),
("San Antonio"),
("San Antonio Abad"),
("San Cosme"),
("San Joaquín"),
("San Juan de Letrán"),
("San Lázaro"),
("San Pedro de los Pinos"),
("Santa Anita"),
("Santa Marta"),
("Sevilla"),
("Tacuba"),
("Tacubaya"),
("Talismán"),
("Tasqueña"),
("Tepalcates"),
("Tepito"),
("Terminal Aérea"),
("Tezonco"),
("Tezozómoc"),
("Tláhuac"),
("Tlaltenco"),
("Tlatelolco"),
("UAM-I"),
("Universidad"),
("Valentín Campa"),
("Valle Gómez"),
("Vallejo"),
("Velódromo"),
("Viaducto"),
("Villa de Aragón"),
("Villa de Cortés"),
("Viveros/Derechos Humanos"),
("Xola"),
("Zapata"),
("Zapotitlán"),
("Zaragoza"),
("Zócalo");